### ISSUE TITLE
客户端版本更新记录

### ISSUE THREAD

**Issue by eedalong** [eedalong/Apache-IoTDB-Client-CSharp#21]
该issue下会进行客户端的更新预告与记录，敬请关注！

**Comment by herowzz** [comment]
这个应该通过Release记录更好吧，参考 [jmockdata/releases](https://github.com/jsonzou/jmockdata/releases)
或者wiki，参考 [mockito wiki](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2)
高级一点的可以在Project里记录，参考[Vue Project](https://github.com/vuejs/vue/projects)

**Comment by eedalong** [comment]
客户端0.12.0.3 发布，具体更新信息见[Release板块](https://github.com/eedalong/iotdb-client-csharp/releases/tag/0.12.0.3)

**Comment by eedalong** [comment]
客户端0.12.0.4发布，具体更新信息见[Release板块](https://github.com/eedalong/iotdb-client-csharp/releases/tag/0.12.0.4)
