### ISSUE TITLE
Use Logging Facade

### ISSUE THREAD

**Issue by herowzz** [eedalong/Apache-IoTDB-Client-CSharp#34]
suggest use a logging facade (e.g. Common.Logging or other lib.....) to avoid direct dependencies
so users can select any log library(NLog, Log4Net ... ) which they like.

**Comment by artsiomtserashkovich** [comment]
Good point. But first of all, you have to decide: Is this client will be registered using DI extensions, or it won't be dependent on the DI container.
If it won't be dependent on the DI container, you can use smth like that: https://github.com/dotnet/spark/blob/c79cf8fad49e4760e6f6b4c8fe31a59f0fa306c4/src/csharp/Microsoft.Spark/Services/LoggerServiceFactory.cs
If it will be registered in DI container, here a good example of logging mechanism:

**Comment by maikebing** [comment]
https://github.com/eedalong/Apache-IoTDB-Client-CSharp/blob/e51e272887410779f781d6612f599f4912428c47/src/Apache.IoTDB/SessionPool.cs#L103

**Comment by maikebing** [comment]
@lausannel  可以关闭了。 这个问题已经解决了。 在新版本中。
