### ISSUE TITLE
Refactor the definition of project

### ISSUE THREAD

**Issue by artsiomtserashkovich** [eedalong/Apache-IoTDB-Client-CSharp#44]
Hello. You have a good start point for such library. But you missed some "enterprise"-specific things. Let me provide some tips for your lib.

1.  Rework the structure of your project. It's good practice to keep test and src files separately: https://softwareengineering.stackexchange.com/questions/369504/directory-structure-for-a-net-solution
2.  Introduce templates for contributors. Some example: https://github.com/Azure/azure-sdk-for-net/issues/new/choose
3.  Define flow for code review and chose one of git branch strategy: https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf
4.  Don't forget about SOLID principles during development
5.  Add code analysis rules for project

If you need some help with development - feel free to PM me :)

**Comment by eedalong** [comment]
Thx Buddy! We will look into these point!

**Comment by artsiomtserashkovich** [comment]
@eedalong good example of project structure: https://github.com/dotnet/spark/tree/main/src/csharp

**Comment by artsiomtserashkovich** [comment]
List of best practices which you can use: https://azure.github.io/azure-sdk/general_introduction.html

**Comment by artsiomtserashkovich** [comment]
@eedalong, do you have any discord/slack channel for this project? I would like to contribute into this project :)

**Comment by eedalong** [comment]
@artsiomtserashkovich  yes, we have a slack channel, check this out! https://join.slack.com/share/zt-q70x3wfo-A9hEGeCpTB8OaRcgA5U4rA
