### ISSUE TITLE
Remove *.csproj and *.sln from .gitgnore file

### ISSUE THREAD

**Issue by artsiomtserashkovich** [eedalong/Apache-IoTDB-Client-CSharp#45]
Currently, all csproj and sln files are presented in gitignore file. It's caused problems for contributors to work with your project.

**Comment by eedalong** [comment]
Thx !😊, I'll remove them from gitignore @artsiomtserashkovich

**Comment by eedalong** [comment]
@artsiomtserashkovich  Done~
