### ISSUE TITLE
返回值问题

### ISSUE THREAD

**Issue by logo008** [eedalong/Apache-IoTDB-Client-CSharp#84]
var status = await sessionPool.InsertRecordAsync
这个插入单条记录的方法，插入成功以后返回值为-1，查看数据库确实是已经插入成功。
另外InsertRecordsAsync方法批量插入相同的记录，返回值就是返回0

**Comment by lausannel** [comment]
插入之后server端有报错吗，能否提供一下最小复现代码

**Comment by logo008** [comment]
var rowRecord = new RowRecord(1668404120807, new() { "test1", "test2", "test3" }, new() { "ts1", "ts2", "ts3" });
var status = await sessionPool.InsertRecordAsync("root.test_group.test_device", rowRecord);
if (status == -1)
{
    Console.WriteLine($"写入失败");
}

随便写了一段，能写入成功，但是返回值为-1

**Comment by logo008** [comment]
> 插入之后server端有报错吗，能否提供一下最小复现代码

var rowRecord = new RowRecord(1668404120807, new() { "test1", "test2", "test3" }, new() { "ts1", "ts2", "ts3" });
var status = await sessionPool.InsertRecordAsync("root.test_group.test_device", rowRecord);
if (status == -1)
{
Console.WriteLine($"写入失败");
}

随便写了一段，能写入成功，但是返回值为-1

**Comment by lausannel** [comment]
好的，我们马上调查

**Comment by lausannel** [comment]
@logo008 能具体说一下环境和版本吗？我这里没办法复现，插入返回的状态值是0

**Comment by logo008** [comment]
> @logo008 能具体说一下环境和版本吗？我这里没办法复现，在0.13.3的IoTDB中插入返回的状态值是0

donet6.0
iotdb0.13.3集群（2节点2副本模式）
批量插入的方法InsertRecordsAsync是对的，单记录插入InsertRecordAsync返回值不对

**Comment by lausannel** [comment]
> > @logo008 能具体说一下环境和版本吗？我这里没办法复现，在0.13.3的IoTDB中插入返回的状态值是0
> 
> donet6.0 iotdb0.13.3集群（2节点2副本模式） 批量插入的方法InsertRecordsAsync是对的，单记录插入InsertRecordAsync返回值不对
0.13.x的分布式版本已经没有维护了，只支持单机版本，您可以试一下单机版本
