### ISSUE TITLE
返回值问题

### ISSUE THREAD

**Issue by logo008** [eedalong/Apache-IoTDB-Client-CSharp#89]
安装最新的IoTDB1.0后，单机模式和集群模式插入记录后返回值均为-1，服务器无报错，记录能插入成功。
另外运行你们 lz-1.0 分支的测试代码，也是返回-1
这是之前提的问题：
https://github.com/eedalong/Apache-IoTDB-Client-CSharp/issues/84#issue-1447309442

**Comment by lausannel** [comment]
使用的是两节点两副本模式吗

**Comment by logo008** [comment]
> 使用的是两节点两副本模式吗

3C3D模式

**Comment by lausannel** [comment]
明天之前会解决~

**Comment by lausannel** [comment]
@logo008 您好，我这边使用1.0.0版本3C3D模式和dotnet 7.0测试情况是，单条记录插入返回正常，多条记录批量插入（`InsertRecords`, `InsertAlignedRecords`, `InsertTablets`, `InsertAlignedTablets`）会返回-1，您那边是这一情况吗

**Comment by logo008** [comment]
> 

lz/1.0是这个现象，我数据量大，基本是批量插入

**Comment by lausannel** [comment]
不客气，新版本中已经解决~
