### ISSUE TITLE
IIS中res.HasNext()卡死

### ISSUE THREAD

**Issue by songhejia** [eedalong/Apache-IoTDB-Client-CSharp#94]
环境：
.NET4.6.1 
IIS10.0
Apache.IoTDB --version 1.0.0.2
IoTDB Server version 0.13.0

问题：
MVC项目中，执行最后一条数据后，再调用这个方法res.HasNext()会出现卡死的情况

![image](https://github.com/eedalong/Apache-IoTDB-Client-CSharp/assets/11451712/c4f65909-3cfa-458f-9108-b219d20dcc20)

测试：
跟踪源码后发现：SessionDataSet类FetchResults方法卡死导致的
![image](https://github.com/eedalong/Apache-IoTDB-Client-CSharp/assets/11451712/8e5e9fc3-ba47-406b-a85d-728277a6315e)

**Comment by songhejia** [comment]
补充：
![image](https://github.com/eedalong/Apache-IoTDB-Client-CSharp/assets/11451712/50f4740b-2c56-4cee-a267-ccf4dc4374d5)

**Comment by lausannel** [comment]
马上调查

**Comment by lausannel** [comment]
Fixed in #95. This bug is related to the deadlock produced by `task.Result`. Change to `await` would fix it.
